### ISSUE TITLE
Can't bundle application

### ISSUE THREAD

**Issue by ESISARPI24** [TheOriginalJosh/nativescript-slides#116]
Hello, i'v been using this plugin for weeks but i've never perform a tns run android --bundle until today, and it seems that i can't perform this operation since i have the error: 

ERROR in ../node_modules/nativescript-slides/nativescript-slides.ts
Module build failed: Error: C:\Users\{username}\Documents\my_app\node_modules\nativescript-slides\nativescript-slides.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at NativeScriptAngularCompilerPlugin.getCompiledFile (C:\Users\{username}\Documents\my_app\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\angular_compiler_plugin.ts:921:15)
    at NativeScriptAngularCompilerPlugin.getCompiledFile (C:\Users\{username}\Documents\my_app\node_modules\nativescript-dev-webpack\plugins\NativeScriptAngularCompilerPlugin.ts:63:26)
    at plugin.done.then (C:\Users\{username}\Documents\my_app\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\loader.ts:49:29)
    at <anonymous>
 @ ./views/carousel/carousel.component.ts 5:46-76 6:55-85
 @ ./views/carousel/carousel.module.ts
 @ ./views/views.module.ts
 @ ./app.module.ts
 @ ./main.ts

Did someone had the same error or could provide me some suggestions to dig in?

Also, i'm on version 4.1.0 for NS. 
Thanks for this plugin ! Best Regards.

**Comment by c13andka** [comment]
just delete the .ts file in the folder

**Comment by TheOriginalJosh** [comment]
@ESISARPI24 I'd recommend using the NGX version of the plugin for Angular webpack compatibility
